### ISSUE TITLE
[Hacktoberfest] Elixir - Create a new GraphQL endpoint

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/MediRepo#21]
It's a new feature!

- [ ] install Absinthe
- [ ] create queries and mutations for existing REST endpoints
- [ ] create a playground to GraphQL

**Comment by TheEndIsNear** [comment]
If you don't have any takers yet, I wouldn't mind taking a stab at this one. Have elixir experience and have played around a bit with Absinthe, and would like to learn more.

**Comment by AndrGab** [comment]
Hi @TheEndIsNear be my guest. I will assign it to you
