### ISSUE TITLE
[Hacktoberfest] Elixir -  Architectural improvements

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/MediRepo#5]
Separate modules in new contexts

**Comment by yunsuklee** [comment]
Hey! May I be assigned this issue?

**Comment by AndrGab** [comment]
Please, be my guest

**Comment by yunsuklee** [comment]
I'll dive into it!

**Comment by yunsuklee** [comment]
Hey, I've been trying to read upon it, but it seems I don't have the knowledge to get this done yet, my bad :c

**Comment by AndrGab** [comment]
It's OK @yunsuklee 
try another one, or include a new feature.
New features are welcome.

**Comment by SahilAnower** [comment]
Hey I am interested in this. I will tell you till the EOD to assign me or not! Thanks

**Comment by AndrGab** [comment]
nice, I'm waiting for it
