### ISSUE TITLE
[Hacktoberfest] Modify table's columns names to English

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/MediRepo#6]
Bulletin columns are in Portuguese
```  schema "bulletins" do
    field :nome, :string
    field :dt_nascimento, :date
    field :geral, :string
    field :pressao, :string
    field :consciencia, :string
    field :febre, :string
    field :respiracao, :string
    field :diurese, :string
    field :obs, :string
    field :medico, :string
    field :dt_assinatura, :date
    field :atendimento, :integer
    field :cd_paciente, :integer
```
- Translate them to English
- Needs Opening a PR in FrontEnd to receive new information

**Comment by sukalyanbisui** [comment]
assign this issue to me. english translation ready. 
 field :name, :string
    field :dt_birth, :date
    field :general, :string
    field :pressure, :string
    field :conscience, :string
    field :fever, :string
    field :breathing, :string
    field :diuresis, :string
    field :notes/comments, :string
    field :doctor, :string
    field :dt_signature, :date
    field :attendance, :integer
    field :cd_patient, :integer

**Comment by AndrGab** [comment]
Hi @sukalyanbisui 
Open a Pr with translated fields, you have to change the migrations too and de frontend. Is it OK?

**Comment by AndrGab** [comment]
Fixed thx to @affanmustafa 
https://github.com/AndrGab/MediRepo/pull/13
